//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLTableDependencyDiagram.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLTableDependencyDiagram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480678_files_folders_15 {
            get {
                object obj = ResourceManager.GetObject("_1453480678_files_folders_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480682_Table_16x16 {
            get {
                object obj = ResourceManager.GetObject("_1453480682_Table_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480689_table_tab_search {
            get {
                object obj = ResourceManager.GetObject("_1453480689_table_tab_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480695_table_add {
            get {
                object obj = ResourceManager.GetObject("_1453480695_table_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480700_table_edit {
            get {
                object obj = ResourceManager.GetObject("_1453480700_table_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480710_table_sum {
            get {
                object obj = ResourceManager.GetObject("_1453480710_table_sum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480734_table_accept {
            get {
                object obj = ResourceManager.GetObject("_1453480734_table_accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480774_040 {
            get {
                object obj = ResourceManager.GetObject("_1453480774_040", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480786_041 {
            get {
                object obj = ResourceManager.GetObject("_1453480786_041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480802_database_add {
            get {
                object obj = ResourceManager.GetObject("_1453480802_database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1453480812_database_save {
            get {
                object obj = ResourceManager.GetObject("_1453480812_database_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calculator16 {
            get {
                object obj = ResourceManager.GetObject("calculator16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^Server\[[^\]]*\]/Database\[@Name=&apos;(?&lt;Database&gt;[^&apos;]*)&apos;\]/Table\[@Name=&apos;(?&lt;Table&gt;[^&apos;]*)&apos; and @Schema=&apos;(?&lt;Schema&gt;[^&apos;]*)&apos;\]/Column\[@Name=&apos;(?&lt;Column&gt;[^&apos;]*)&apos;\]$.
        /// </summary>
        internal static string ColumnRegEx {
            get {
                return ResourceManager.GetString("ColumnRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hammer16 {
            get {
                object obj = ResourceManager.GetObject("hammer16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*display information regarding what databases are backup*/
        ///SELECT db.NAME
        ///	,CASE 
        ///		WHEN MAX(b.backup_finish_date) IS NULL
        ///			THEN &apos;No Backup&apos;
        ///		ELSE convert(VARCHAR(100), MAX(b.backup_finish_date))
        ///		END AS [Last Backup Finish Date]
        ///FROM sys.databases db
        ///LEFT OUTER JOIN msdb.dbo.backupset b ON db.NAME = b.database_name
        ///	AND b.type = &apos;D&apos;
        ///WHERE db.database_id NOT IN (2)
        ///GROUP BY db.NAME
        ///ORDER BY 2 DESC
        ///
        ////*display the backup device names*/
        ///SELECT DISTINCT physical_device_name AS [Physical Devi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLBackupInfo {
            get {
                return ResourceManager.GetString("SQLBackupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) AS COUNT FROM [{0}].[{1}].
        /// </summary>
        internal static string SQLCount {
            get {
                return ResourceManager.GetString("SQLCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH cte AS (SELECT {0},
        ///row_number() OVER(PARTITION BY {0} ORDER BY {0}) AS [rank]
        ///FROM {1})
        ///
        ////*Run SQL to find duplicates, when you are happy to remove the duplicates, 
        ///uncomment the Delete statement and comment out the Select statement */
        ///
        ///SELECT * FROM cte WHERE [rank] &gt; 1
        ///--DELETE cte WHERE [rank] &gt; 1.
        /// </summary>
        internal static string SQLDuplicateColumnData {
            get {
                return ResourceManager.GetString("SQLDuplicateColumnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  L.request_session_id AS SPID,
        ///DB_NAME(L.resource_database_id) AS DatabaseName,
        ///O.Name AS LockedObjectName,
        ///P.object_id AS LockedObjectId,
        ///L.resource_type AS LockedResource,
        ///L.request_mode AS LockType,
        ///ST.text AS SqlStatementText,
        ///ES.login_name AS LoginName,
        ///ES.host_name AS HostName,
        ///TST.is_user_transaction as IsUserTransaction,
        ///AT.name as TransactionName,
        ///CN.auth_scheme as AuthenticationMethod
        ///FROM     sys.dm_tran_locks L
        ///JOIN sys.partitions P ON P.hobt_id = L.resource_associated_entity [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLKillTrans {
            get {
                return ResourceManager.GetString("SQLKillTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [{0}].[{1}].
        /// </summary>
        internal static string SQLSelect {
            get {
                return ResourceManager.GetString("SQLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SERVERPROPERTY(&apos;MachineName&apos;) AS Host
        ///	,SERVERPROPERTY(&apos;InstanceName&apos;) AS Instance
        ///	,SERVERPROPERTY(&apos;Edition&apos;) AS Edition
        ///	,/*shows 32 bit or 64 bit*/
        ///	SERVERPROPERTY(&apos;ProductLevel&apos;) AS ProductLevel
        ///	,/* RTM or SP1 etc*/
        ///	CASE SERVERPROPERTY(&apos;IsClustered&apos;)
        ///		WHEN 1
        ///			THEN &apos;CLUSTERED&apos;
        ///		ELSE &apos;STANDALONE&apos;
        ///		END AS ServerType
        ///	,@@VERSION AS VersionNumber.
        /// </summary>
        internal static string SQLSerInfo {
            get {
                return ResourceManager.GetString("SQLSerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^Server\[[^\]]*\]/Database\[[^\]]*\]/Table\[[^\]]*\]$.
        /// </summary>
        internal static string TableRegEx {
            get {
                return ResourceManager.GetString("TableRegEx", resourceCulture);
            }
        }
    }
}
