// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DiagramGeneratorIX.Command
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidDiagramGeneratorIXPackageString = "d62658ad-de88-4073-b690-0bd9f6ab4127";
        public static Guid guidDiagramGeneratorIXPackage = new Guid(guidDiagramGeneratorIXPackageString);

        public const string guidDiagramGeneratorIXPackageCmdSetString = "1b98a955-b6ca-4bba-a759-d0b67184c7f7";
        public static Guid guidDiagramGeneratorIXPackageCmdSet = new Guid(guidDiagramGeneratorIXPackageCmdSetString);

        public const string guidImagesString = "3801ecf4-b9a6-4fea-9954-f9951e625779";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ToolsMenuId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}