//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SsmsTableDependencyDiagram.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SsmsTableDependencyDiagram.Domain.Resources.TextStrings", typeof(TextStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseNode.
        /// </summary>
        public static string BaseNode {
            get {
                return ResourceManager.GetString("BaseNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnDataType.
        /// </summary>
        public static string ColumnDataType {
            get {
                return ResourceManager.GetString("ColumnDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataroot.
        /// </summary>
        public static string dataroot {
            get {
                return ResourceManager.GetString("dataroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForeignKey.
        /// </summary>
        public static string ForeignKey {
            get {
                return ResourceManager.GetString("ForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrimaryKey.
        /// </summary>
        public static string IsPrimaryKey {
            get {
                return ResourceManager.GetString("IsPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneToMany.
        /// </summary>
        public static string OneToMany {
            get {
                return ResourceManager.GetString("OneToMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneToOne.
        /// </summary>
        public static string OneToOne {
            get {
                return ResourceManager.GetString("OneToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select database.
        /// </summary>
        public static string PleaseSelectDatabase {
            get {
                return ResourceManager.GetString("PleaseSelectDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select table.
        /// </summary>
        public static string PleaseSelectTable {
            get {
                return ResourceManager.GetString("PleaseSelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrimaryKey.
        /// </summary>
        public static string PrimaryKey {
            get {
                return ResourceManager.GetString("PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File:.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema-instance.
        /// </summary>
        public static string schIns {
            get {
                return ResourceManager.GetString("schIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. 
        ///Message: {0}
        ///Please review the ActivityLog.xml file for more information..
        /// </summary>
        public static string StandardErrorMessage {
            get {
                return ResourceManager.GetString("StandardErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string StandardErrorMessageTitle {
            get {
                return ResourceManager.GetString("StandardErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE_NAME.
        /// </summary>
        public static string TABLE_NAME {
            get {
                return ResourceManager.GetString("TABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableId.
        /// </summary>
        public static string TableId {
            get {
                return ResourceManager.GetString("TableId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:schemas-microsoft-com:officedata.
        /// </summary>
        public static string urn {
            get {
                return ResourceManager.GetString("urn", resourceCulture);
            }
        }
    }
}
